name: tareal10
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Paquete para trabajar con mapas y OpenStreetMap
  flutter_map: ^6.1.0

  # Paquete para trabajar con coordenadas latitud y longitud
  latlong2: ^0.9.1

  # Paquete para iconos de Cupertino en iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting para buenas prácticas
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Aquí puedes agregar assets si necesitas imágenes o recursos externos
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Si necesitas agregar fuentes personalizadas, puedes hacerlo aquí
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
